# Development Docker Compose configuration
# Use this for development with hot-reloading and debug mode

version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-dev
    ports:
      - "11434:11434"
    volumes:
      - ollama_data_dev:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_DEBUG=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5

  chat-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: chat-backend-dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - OLLAMA_URL=http://ollama:11434
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped

  streamlit-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: streamlit-frontend-dev
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://chat-backend:5000
      - STREAMLIT_SERVER_RUNONSTARTUP=true
      - STREAMLIT_SERVER_FILECHANGES=true
    depends_on:
      - chat-backend
    restart: unless-stopped

volumes:
  ollama_data_dev: